language: node_js
node_js: stable
#缓存
cache:
  directories:
  - node_modules

# S: Build Lifecycle
install:
  - npm install


before_script:
- export TZ='Asia/Shanghai'
 # - npm install -g gulp

script:
  - hexo clean
  - hexo generate

after_script:
  - git config user.name "harveyspace"
  - git config user.email "harveyer@163.com"
  - sed -i "s/github_token/${github_token}/g" ./_config.yml
  - cat ./_config.yml
  - hexo g -d
branches:
  only:
    - hexo
env:
 global:
   - GH_REF: github.com/vpinfra/vpinfra.github.io.git
